import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { doc, getDoc, collection, getDocs } from 'firebase/firestore';
import { db } from '../../firebase';
import { useAuth } from '../../contexts/AuthContext';
import { TestData, WeeklyRange } from '../../types';
import Header from '../common/Header';

function getTodayIndex(): number {
  const day = new Date().getDay();
  return day === 0 ? 6 : day - 1; // 0=月〜6=日
}

const TestWeekPage: React.FC = () => {
  const { classId, rangeId } = useParams<{ classId: string; rangeId: string }>();
  const navigate = useNavigate();
  const { currentUser } = useAuth();
  const [range, setRange] = useState<WeeklyRange | null>(null);
  const [weekTests, setWeekTests] = useState<TestData[]>([]);
  const [loading, setLoading] = useState(true);

  const todayIdx = getTodayIndex(); // 0=月〜4=金, 5=土, 6=日

  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  useEffect(() => {
    const load = async () => {
      if (!classId || !rangeId || !currentUser) return;

      const rangeDoc = await getDoc(doc(db, 'classes', classId, 'ranges', rangeId));
      if (!rangeDoc.exists()) { setLoading(false); return; }
      const r = { id: rangeDoc.id, ...rangeDoc.data() } as WeeklyRange;
      setRange(r);

      const testsSnap = await getDocs(collection(db, 'classes', classId, 'tests'));
      const matched = testsSnap.docs
        .map((d) => ({ id: d.id, ...d.data() } as TestData))
        .filter((t) => t.startId >= r.startId && t.endId <= r.endId)
        .sort((a, b) => {
          const aKey = a.sortKey ?? Number.MAX_SAFE_INTEGER;
          const bKey = b.sortKey ?? Number.MAX_SAFE_INTEGER;
          if (aKey !== bKey) return aKey - bKey;
          return a.startId - b.startId;
        });
      setWeekTests(matched);
      setLoading(false);
    };
    load();
  }, [classId, rangeId, currentUser]);

  // 自動生成テストのsortKeyを週内の相対位置（0=月〜4=金, 5=まとめ）に変換
  const autoTests = weekTests.filter((t) => t.isAutoGenerated && t.sortKey !== undefined);
  const minSortKey = autoTests.length > 0
    ? Math.min(...autoTests.map((t) => t.sortKey!))
    : null;

  const getTodayRelative = (t: TestData): number | null => {
    if (!t.isAutoGenerated || t.sortKey === undefined || minSortKey === null) return null;
    return t.sortKey - minSortKey; // 0=月, 1=火, 2=水, 3=木, 4=金, 5=まとめ
  };

  // 土曜はまとめ(5)を今日扱い、日曜は対応なし
  const todayRelative = todayIdx <= 4 ? todayIdx : todayIdx === 5 ? 5 : null;

  if (loading) {
    return (
      <>
        <Header />
        <div style={styles.loading}>読み込み中...</div>
      </>
    );
  }

  return (
    <>
      <Header />
      <div style={styles.page}>
        <button style={styles.backBtn} onClick={() => navigate(-1)}>← 戻る</button>

        <div style={styles.headerCard}>
          <div style={styles.headerLabel}>チェックテスト</div>
          <div style={styles.headerTitle}>{range?.weekLabel}</div>
          {range && (
            <div style={styles.headerRange}>
              No.{range.startId} 〜 No.{range.endId}　全{range.endId - range.startId + 1}語
            </div>
          )}
        </div>

        {weekTests.length === 0 ? (
          <div style={styles.empty}>このWeekのチェックテストはまだありません</div>
        ) : (
          <div style={styles.list}>
            {weekTests.map((t) => {
              const rel = getTodayRelative(t);
              const isToday = rel !== null && todayRelative !== null && rel === todayRelative;
              return (
                <button
                  key={t.id}
                  style={{
                    ...styles.testCard,
                    ...(isToday ? styles.testCardToday : {}),
                  }}
                  onClick={() => navigate(`/test/${classId}/${t.id}`)}
                >
                  <div style={styles.cardContent}>
                    <div style={styles.testTitle}>
                      {range ? t.title.replace(range.weekLabel, '').replace(/^[　\s]+/, '') : t.title}
                      {isToday && <span style={styles.todayBadge}>今日</span>}
                    </div>
                    <div style={styles.testRange}>No.{t.startId}〜{t.endId}</div>
                  </div>
                  <div style={{ ...styles.arrow, color: '#1a3a6b' }}>→</div>
                </button>
              );
            })}
          </div>
        )}
      </div>
    </>
  );
};

const styles: { [key: string]: React.CSSProperties } = {
  page: { maxWidth: 600, margin: '0 auto', padding: '20px 16px 60px' },
  loading: { display: 'flex', justifyContent: 'center', alignItems: 'center', height: '50vh', fontSize: 18, color: '#6b7280' },
  backBtn: { padding: '8px 16px', background: '#f3f4f6', borderRadius: 8, fontSize: 14, color: '#4b5563', marginBottom: 16, border: 'none', cursor: 'pointer' },
  headerCard: {
    background: '#7c3aed',
    borderRadius: 16,
    padding: '20px 20px 18px',
    marginBottom: 20,
    color: '#fff',
  },
  headerLabel: { fontSize: 11, color: '#ddd6fe', fontWeight: 600, letterSpacing: '0.08em', marginBottom: 4 },
  headerTitle: { fontSize: 22, fontWeight: 700, marginBottom: 4 },
  headerRange: { fontSize: 13, color: '#93c5fd' },
  list: { display: 'flex', flexDirection: 'column' as const, gap: 10 },
  testCard: {
    display: 'flex',
    alignItems: 'center',
    gap: 14,
    background: '#fff',
    borderRadius: 14,
    padding: '14px 16px',
    boxShadow: '0 1px 4px rgba(0,0,0,0.06)',
    border: '1.5px solid transparent',
    cursor: 'pointer',
    textAlign: 'left' as const,
    width: '100%',
    transition: 'box-shadow 0.15s',
  },
  testCardToday: {
    border: '1.5px solid #7c3aed',
    boxShadow: '0 2px 10px rgba(124,58,237,0.14)',
  },
  cardContent: { flex: 1 },
  testTitle: { fontSize: 14, fontWeight: 700, color: '#1a3a6b', marginBottom: 3, display: 'flex', alignItems: 'center', gap: 6, flexWrap: 'wrap' as const },
  todayBadge: { fontSize: 10, background: '#7c3aed', color: '#fff', padding: '1px 7px', borderRadius: 99, fontWeight: 600 },
  testRange: { fontSize: 13, color: '#6b7280' },
  arrow: { fontSize: 18, flexShrink: 0 },
  empty: { textAlign: 'center', padding: 40, color: '#9ca3af', fontSize: 15 },
};

export default TestWeekPage;
