export interface Word {
  id: number;
  english: string;
  japanese: string;
  pos: string;
  example: string;
  pronunciation?: string;
  derivatives?: string;
  mnemonic?: string;
}

export type WordStatus = 'unlearned' | 'review' | 'mastered';

export interface WordProgress {
  wordId: number;
  status: WordStatus;
  consecutiveCorrect: number;
  lastStudied?: Date;
}

export interface UserProfile {
  uid: string;
  email: string;
  displayName: string;
  furigana?: string;
  role: 'student' | 'admin';
  classIds: string[];
  createdAt: Date;
}

export interface ClassData {
  id: string;
  name: string;
  adminId: string;
  coAdminIds?: string[];
  studentIds: string[];
  wordSetId?: string;
  maintenanceEnabled?: boolean;
  createdAt: Date;
}

export interface WeeklyRange {
  id: string;
  classId: string;
  weekLabel: string;
  startId: number;
  endId: number;
  lessonDate: string;
}

export interface StudySession {
  userId: string;
  classId: string;
  rangeId: string;
  currentIndex: number;
  mode: 'normal' | 'review';
  lastUpdated: Date;
}

export interface TestData {
  id: string;
  classId: string;
  title: string;
  startId: number;
  endId: number;
  createdAt: Date;
  isActive: boolean;
  isAutoGenerated?: boolean;
  sortKey?: number;
}

export interface TestResult {
  id: string;
  testId: string;
  userId: string;
  score: number;
  totalQuestions: number;
  wrongWords: number[];
  completedAt: Date;
}

export interface TestQuestion {
  wordId: number;
  english: string;
  correctAnswer: string;
  choices: string[];
}

// ===== 文法（開発中・管理者のみ） =====

// 各週のテーマ固有の思考フロー
export interface GrammarThinkingStep {
  key: string;
  label: string;
  hint: string;
}

// 週（Firestoreに保存）
export interface GrammarWeek {
  id: string;
  classId: string;
  weekNumber: number;           // 1, 2, 3, ...
  weekLabel: string;            // "第1週 4月1週目"
  theme: string;                // "品詞(1)"
  lessonDate?: string;
  thinkingFlow: GrammarThinkingStep[];
  problemIds: string[];         // このweekに属する問題IDの順序
}

// 選択肢ごとの解説（なぜ正解／なぜ不正解か）
export interface GrammarChoice {
  text: string;
  isCorrect: boolean;
  reason?: string;              // この選択肢が誤りである理由（ある場合）
}

// 段階的淘汰ステップで使う2択（ユーザーに判断させる小問）
export interface EliminationOption {
  label: string;
  isCorrect: boolean;
}

// ステップ。正解選択でeliminateOriginalIndexesの選択肢が淘汰される
export interface EliminationStep {
  stepKey: string;              // thinkingFlowのkeyと対応（任意）
  question: string;
  options: EliminationOption[];
  eliminateOriginalIndexes: number[]; // GrammarProblem.choices の元のindexで指定
  hint?: string;                // 間違えたときに出す補足
}

// 問題本体（Firestoreに保存）
export interface GrammarProblem {
  id: string;
  classId: string;
  weekId: string;
  sentence: string;             // "Let's ( ) about that problem later."
  choices: GrammarChoice[];     // 4つ。isCorrectはひとつのみtrue
  primaryStepKey: string;       // この問題でメインに問われるthinkingFlowのkey
  explanation: string;          // 正解の詳しい解説
  commonTip?: string;           // テーマ共通のヒント
  eliminationSteps?: EliminationStep[]; // 段階的淘汰モード用
}

export type GrammarStatus = 'unlearned' | 'review' | 'mastered';

// 進捗（ユーザーごと・問題ごと）
export interface GrammarProgress {
  problemId: string;
  status: GrammarStatus;
  consecutiveCorrect: number;
  mistakeCount: number;
  lastAnswered?: Date;
  stepMistakes?: { [stepKey: string]: number };
}
